Traceback (most recent call last):
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/jupyter_cache-0.4.1-py3.7.egg/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Timing the use of numpy functions
import numpy as np

start_time = perf_counter()

n_arr = np.arange(1, 1001)
s = np.sum( (-1)**n_arr/n_arr )

np_time = perf_counter() - start_time

print('Using NumPy:')
print('The value of the sum is:', s)
print('The time taken to compute the sum is:', np_time)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-3-b9e5be40c854>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#Timing the use of numpy functions[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mstart_time[0m [0;34m=[0m [0mperf_counter[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

